version: "3.0"

services:
    redis:
        image: redis:latest
        ports:
          - 6379:6379
    kafka:
        image: bitnami/kafka
        ports:
          - 9092:9092
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafka-ui:
        image: provectuslabs/kafka-ui
        ports:
          - 9000:8080
        environment:
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_NAME: local
    zookeeper:
        image: bitnami/zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
