version: "3.0"

services:
    redis:
        image: redis:latest
        ports:
          - 6379:6379
    kafka:
        image: bitnami/kafka
        ports:
          - 9092:9092
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9093,EXTERNAL://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
        depends_on:
            - zookeeper
    kafka-ui:
        image: provectuslabs/kafka-ui
        ports:
          - 9000:8080
        environment:
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
            KAFKA_CLUSTERS_0_NAME: local
        depends_on:
            - kafka
    zookeeper:
        image: bitnami/zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
