name: Player

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Player
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_SECRET }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: dockerfiles/player/Dockerfile
          tags: ghcr.io/atomgenie/player:latest
          context: .
