name: YoutubeDL

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Youtube DL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./dockerfiles/youtubedl/Dockerfile
          tags: atomgenie/discord-sound/youtubedl:latest
