apiVersion: apps/v1
kind: Deployment
metadata:
    name: player
    labels:
        name: player
spec:
    replicas: 1
    selector:
        matchLabels:
            name: player
    template:
        metadata:
            labels:
                name: player
        spec:
            containers:
            - name: player
              image: {{ .Values.player.image }}
              env:
                - name: REDIS_URL
                  value: {{ .Release.Name }}-redis-master:6379
                - name: YOUTUBE_DL_TOPIC
                  value: youtubedl
                - name: YOUTUBE_DL_DONE_TOPIC
                  value: youtubedl_done
                - name: DISCORD_TOKEN
                  value: {{ required "DISCORD_TOKEN" .Values.DISCORD_TOKEN }}
                - name: YOUTUBE_URL
                  value: http://youtube-dl:9000
