apiVersion: apps/v1
kind: Deployment
metadata:
    name: youtube-dl
    labels:
        name: youtube-dl
spec:
    replicas: {{ .Values.youtubedl.replicas }}
    selector:
        matchLabels:
            name: youtube-dl
    template:
        metadata:
            labels:
                name: youtube-dl
        spec:
            containers:
            - name: youtube-dl
              image: {{ .Values.youtubedl.image }}
              env:
                - name: REDIS_URL
                  value: {{ .Release.Name }}-redis-master.default.svc.cluster.local:6379
                - name: YOUTUBE_DL_DONE_TOPIC
                  value: youtubedl_done
                - name: YOUTUBE_DL_TOPIC
                  value: youtubedl

---

apiVersion: v1
kind: Service
metadata:
  name: youtube-dl
spec:
  selector:
    name: youtube-dl
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
