apiVersion: apps/v1
kind: Deployment
metadata:
    name: youtube-dl
    labels:
        name: youtube-dl
spec:
    replicas: {{ .Values.youtubedl.replicas }}
    selector:
        matchLabels:
            name: youtube-dl
    template:
        metadata:
            labels:
                name: youtube-dl
        spec:
            containers:
            - name: youtube-dl
              image: {{ .Values.youtubedl.image }}
              env:
                - name: REDIS_URL
                  value: {{ .Release.Name }}-redis-master:6379
                - name: YOUTUBE_DL_DONE_TOPIC
                  value: youtubedl_done
                - name: YOUTUBE_DL_TOPIC
                  value: youtubedl
