apiVersion: apps/v1
kind: Deployment
metadata:
    name: youtube-dl
    labels:
        name: youtube-dl
spec:
    replicas: 1
    selector:
        matchLabels:
            name: youtube-dl
    template:
        metadata:
            labels:
                name: youtube-dl
        spec:
            containers:
            - name: youtube-dl
              image: {{ .Values.youtubedlImage }}
              env:
                - name: REDIS_URL
                  value: {{ .Release.Name }}-redis-master:6379

