apiVersion: apps/v1
kind: Deployment
metadata:
    name: youtube-dl
    labels:
        name: youtube-dl
spec:
    replicas: {{ .Values.youtubedl.replicas }}
    selector:
        matchLabels:
            name: youtube-dl
    template:
        metadata:
            labels:
                name: youtube-dl
        spec:
            containers:
            - name: youtube-dl
              image: {{ .Values.youtubedl.image }}
              env:
                - name: REDIS_URL
                  value: {{ .Release.Name }}-redis-master:6379
                - name: KAFKA_URL
                  value: {{ .Release.Name}}-kafka:9092
                - name: YOUTUBE_DL_TOPIC
                  value: youtubedl
                - name: YOUTUBE_DL_DONE_TOPIC
                  value: youtubedl_done

---

apiVersion: v1
kind: Pod
metadata:
    name: bastion
spec:
    containers:
        -
            image: ubuntu:21.04
            name: bastion-img
            command: ["sh", "-c", "tail -f /dev/null"]
